coverage:
  range: 80..100
  status:
    project:
      default: off
      01_punk_api:
        flags: packages/workshops/01_punk_api

flags:
  packages/workshops/01_punk_api:
    paths:
      - packages/workshops/01_punk_api
