coverage:
  range: 80..100
  status:
    project:
      default: off
      01_punk_api:
        flags: packages/workshops/01_punk_api
      basic_layout_solution:
        flags: basic_layout_solution

flags:
  packages/workshops/01_punk_api:
    paths:
      - packages/workshops/01_punk_api
