name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build_flutter_packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: [
        ]
        channel: ["stable"]

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter packages get
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: flutter test --coverage --coverage-path coverage/lcov.info
        working-directory: ${{ matrix.package }}

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          file: ./${{ matrix.package }}/coverage/lcov.info
