name: docs

on:
  push:
    branches:
      - master
    path:
      - ".github/workflows/docs.yml"
      - "package.json"
      - ".prettierignore"
      - "docs/**"
  pull_request:
    branches:
      - master
    path:
      - ".github/workflows/docs.yml"
      - "package.json"
      - ".prettierignore"
      - "docs/**"

jobs:
  vuepress_site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Install dependencies
        run: yarn
      - name: Lint
        run: yarn lint
      - name: Build docs
        run: yarn docs:build
  build:
    needs: [vuepress_site]
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo 'noop'
