name: flutter_workshops

on:
  push:
    branches:
      - master
    path:
      - ".github/workflows/flutter_workshops.yml"
      - "packages/workshops/01_punk_api/**"
  pull_request:
    branches:
      - master
    path:
      - ".github/workflows/flutter_workshops.yml"
      - "packages/workshops/01_punk_api/**"

jobs:
  flutter_workshops_samples:
    runs-on: ubuntu-latest
    fail-fast: false
    strategy:
      matrix:
        package: ["packages/workshops/01_punk_api"]
        channel: ["stable"]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}

      - name: Install dependencies
        run: flutter packages get
        working-directory: ${{ matrix.package }}

      - name: Analyze
        run: flutter analyze
        working-directory: ${{ matrix.package }}

      - name: Run tests
        run: flutter test --coverage --coverage-path coverage/lcov.info
        working-directory: ${{ matrix.package }}

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          file: ./${{ matrix.package }}/coverage/lcov.info
  build:
    needs: [flutter_workshops_samples]
    runs-on: ubuntu-latest
    steps:
      - name: noop
        run: echo 'noop'
